#!/usr/bin/env python3
"""Generate the frontend's public contract types from canonical OpenAPI."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence


ROOT = Path(__file__).resolve().parents[1]


def _literal(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(value, ensure_ascii=False)


def _reference_name(reference: str) -> str:
    prefix = "#/components/schemas/"
    if not reference.startswith(prefix):
        raise ValueError("unsupported OpenAPI reference: {}".format(reference))
    return reference[len(prefix):]


def _typescript_type(schema: Dict[str, Any]) -> str:
    if "$ref" in schema:
        return _reference_name(str(schema["$ref"]))
    if "const" in schema:
        if schema["const"] == "v1":
            return "SchemaVersion"
        if schema["const"] == "greenlight.v1":
            return "GreenlightPolicyVersion"
        return _literal(schema["const"])
    if "enum" in schema:
        return " | ".join(_literal(value) for value in schema["enum"])
    if "anyOf" in schema:
        members: List[str] = []
        for item in schema["anyOf"]:
            member = _typescript_type(item)
            if member not in members:
                members.append(member)
        return " | ".join(members)

    value_type = schema.get("type")
    if value_type == "array":
        item_type = _typescript_type(schema.get("items", {}))
        if " | " in item_type:
            item_type = "({})".format(item_type)
        return "{}[]".format(item_type)
    if value_type == "object":
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return "Record<string, {}>".format(_typescript_type(additional))
        return "Record<string, unknown>"
    if value_type == "string":
        return "string"
    if value_type in {"integer", "number"}:
        return "number"
    if value_type == "boolean":
        return "boolean"
    if value_type == "null":
        return "null"
    if not schema:
        return "unknown"
    raise ValueError("unsupported OpenAPI schema fragment: {}".format(schema))


def generate(document: Dict[str, Any]) -> str:
    schemas = document.get("components", {}).get("schemas")
    if not isinstance(schemas, dict):
        raise ValueError("OpenAPI components.schemas is missing")

    lines = [
        "/**",
        " * GENERATED from backend/openapi.json by scripts/generate_ts_contracts.py.",
        " * Do not edit this file directly; update the Pydantic contract and regenerate it.",
        " */",
        "",
        'export const SCHEMA_VERSION = "v1" as const;',
        'export const GREENLIGHT_POLICY_VERSION = "greenlight.v1" as const;',
        "",
        "export type SchemaVersion = typeof SCHEMA_VERSION;",
        "export type GreenlightPolicyVersion = typeof GREENLIGHT_POLICY_VERSION;",
        "",
    ]

    for name in sorted(schemas):
        schema = schemas[name]
        if not isinstance(schema, dict):
            raise ValueError("schema {} is not an object".format(name))
        if schema.get("type") == "object" and "properties" in schema:
            required = set(schema.get("required", []))
            lines.append("export interface {} {{".format(name))
            for property_name, property_schema in schema["properties"].items():
                optional = "" if property_name in required else "?"
                lines.append(
                    "  {}{}: {};".format(
                        property_name,
                        optional,
                        _typescript_type(property_schema),
                    )
                )
            lines.extend(["}", ""])
        else:
            lines.extend([
                "export type {} = {};".format(name, _typescript_type(schema)),
                "",
            ])
    return "\n".join(lines).rstrip() + "\n"


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--openapi", default="backend/openapi.json")
    parser.add_argument("--output", default="src/api/contracts.ts")
    parser.add_argument("--check", action="store_true")
    return parser


def main(argv: Optional[Sequence[str]] = None) -> int:
    arguments = build_parser().parse_args(argv)
    source = ROOT / arguments.openapi
    target = ROOT / arguments.output
    document = json.loads(source.read_text(encoding="utf-8"))
    generated = generate(document)
    if arguments.check:
        if not target.exists() or target.read_text(encoding="utf-8") != generated:
            raise SystemExit("TypeScript contract drift: regenerate {}".format(target))
        print("TypeScript contracts match canonical OpenAPI.")
        return 0
    target.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
